- hosts: switches
  gather_facts: no
  connection: local

  tasks:
    - name: Configure LAG groups
      cisco.ios.ios_lag_interfaces:
        config:
          - name: Port-channel01
            members:
              - member: GigabitEthernet1/0/1
                mode: auto
              - member: GigabitEthernet1/0/2
                mode: auto
              - member: GigabitEthernet1/0/3
                mode: auto
              - member: GigabitEthernet1/0/4
                mode: auto

          - name: Port-channel02
            members:
              - member: GigabitEthernet1/0/9
                mode: auto
              - member: GigabitEthernet1/0/10
                mode: auto

          - name: Port-channel03
            members:
              - member: GigabitEthernet1/0/11
                mode: auto
              - member: GigabitEthernet1/0/12
                mode: auto

          - name: Port-channel04
            members:
              - member: GigabitEthernet1/0/13
                mode: auto
              - member: GigabitEthernet1/0/14
                mode: auto
        state: rendered

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l2_interfaces:
        config:
          - name: Port-channel01
            mode: trunk
            trunk:
              allowed_vlans: 1,10,20,30,40,50
              native_vlan: 1
              encapsulation: dot1q
          - name: Port-channel02
            mode: trunk
            trunk:
              allowed_vlans: 1,20,40
              native_vlan: 1
              encapsulation: dot1q
          - name: Port-channel03
            mode: trunk
            trunk:
              allowed_vlans: 1,10,20,30,40,50
              native_vlan: 1
              encapsulation: dot1q
          - name: Port-channel04
            mode: trunk
            trunk:
              allowed_vlans: 1,10,20,30,40,50
              native_vlan: 1
              encapsulation: dot1q
          - name: GigabitEthernet1/0/32
            mode: trunk
            trunk:
              allowed_vlans: 10,20,30,40,50
              native_vlan: 20
              encapsulation: dot1q
          - name: GigabitEthernet1/0/48
            mode: access
            access:
              vlan: 40
        state: rendered
