- hosts: switches
  gather_facts: no
  connection: local

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/48
            mode: trunk
            trunk:
              allowed_vlans: 1,10,20,30,40,50
              native_vlan: 1
              encapsulation: dot1q
          - name: GigabitEthernet1/0/30
            mode: trunk
            trunk:
              allowed_vlans: 10,20,30,40,50
              native_vlan: 20
              encapsulation: dot1q
          - name: GigabitEthernet1/0/31
            mode: trunk
            trunk:
              allowed_vlans: 10,20,30,40,50
              native_vlan: 20
              encapsulation: dot1q
          - name: GigabitEthernet1/0/32
            mode: trunk
            trunk:
              allowed_vlans: 10,20,30,40,50
              native_vlan: 20
              encapsulation: dot1q
        state: replaced
