#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---
- hosts: all
  become: true

  tasks:
    - name: Delete initial user
      user:
        name: "thault"
        state: absent
        remove: true

#    - name: Set a hostname
#      ansible.builtin.hostname:
#ls        name:
