---
- hosts: all
  become: true
  vars_files:
    - vars/GlusterVars.yaml

  tasks:
    - name: Ensure dependencies are installed.
      apt:
        name: dirmngr
        state: present

    - name: Ensure PPA for GlusterFS is present.
      apt_repository:
        repo: 'ppa:gluster/glusterfs-7'
        state: present
        update_cache: true
      register: glusterfs_ppa_added
      when: true

    - name: Ensure GlusterFS will reinstall if the PPA was just added.
      apt:
        name:
          - glusterfs-client
        state: absent
      when: glusterfs_ppa_added.changed
      tags: ['skip_ansible_lint']

    - name: Ensure GlusterFS is installed.
      apt:
        name:
          - glusterfs-client
        state: present
        default_release: ""

    - name: Ensure Gluster volume is mounted.
      mount:
        name: /opt/glust
        src: "{{ glust_host }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
